apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-democratic-snapclass-iscsi
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: org.democratic-csi.iscsi
deletionPolicy: Delete
parameters:
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-democratic-snapclass-nfs
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: org.democratic-csi.nfs
deletionPolicy: Delete
parameters:

