apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "2.6.2"
    helm:
      valueFiles:
      - /helm-values/metallb.yaml
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
