apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-iscsi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    targetRevision: "0.8.3"
    chart: democratic-csi
    helm:
      valueFiles:
        - /helm-values/democratic_iscsi.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
