apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "11.2.2"
    helm:
      parameters:
      - name: env.TZ
        value: "Europe/Berlin"
      values: |
        service:
          type: ingress
          tls:
            commonName: harbor.internetz.cloud
        internalTLS:
          enabled: false
        harborAdminPassword: "topsecureshitbaby"
        externalURL: https://harbor.internetz.cloud
        global:
          storageClass: freenas-iscsi-csi
        notary:
          enabled: false
        core:
          tls:
            existingSecret: 
        ingress:
          certManager: true
          enabled: true
          pathType: ImplementationSpecific
          hosts:
            core: harbor.internetz.cloud
          controller: default
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/hostname: "harbor.internetz.cloud."
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            ingress.kubernetes.io/ssl-redirect: 'false'
            nginx.ingress.kubernetes.io/ssl-redirect: 'false'
            #ingress.kubernetes.io/proxy-body-size: '0'
      # valueFiles:
      #   - /helm-values/harbor.yaml
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true