apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lidarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: lidarr
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: "13.2.0"
    helm:
      values: |
        persistence:
          config:
            enabled: true
            accessMode: "ReadWriteOnce"
            storageClass: "freenas-iscsi-csi"
            size: "5Gi"
            readOnly: false
          media:
            enabled: true
            accessMode: "ReadWriteOnce"
            size: "1000Gi"
            storageClass: "freenas-nfs-csi"
            existingClaim: "shared-media"
            mountPath: "/media"
        ingress:
          main:
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/hostname: "lidarr.internetz.cloud."
              external-dns.alpha.kubernetes.io/target: "46.142.60.21"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              nginx.ingress.kubernetes.io/auth-url: http://authelia.authelia.svc.cluster.local/api/verify
              nginx.ingress.kubernetes.io/auth-signin: https://auth.internetz.cloud
            enabled: true
            hosts:
              - host: lidarr.internetz.cloud
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      port: 7878
            tls:
            - secretName: lidarr-tls
              hosts:
              - lidarr.internetz.cloud
        podSecurityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
