apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lidarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: lidarr
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: "14.0.0"
    helm:
      valueFiles:
        - /helm-values/lidarr.yaml
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
