apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: photoprism
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: "6.2.0"
    helm:
      parameters:
      - name: env.PHOTOPRISM_ADMIN_PASSWORD
        value: "changeme"
      - name: persistence.config.enabled
        value: "true"
      - name: persistence.config.mountPath
        value: "/photoprism/storage"
      - name: persistence.config.accessMode 
        value: "ReadWriteOnce"
      - name: persistence.config.size 
        value: "1Gi"
      - name: persistence.config.storageClass
        value: "freenas-iscsi-csi"
      - name: persistence.originals.enabled
        value: "true"
      - name: persistence.originals.mountPath
        value: "/photoprism/originals"
      - name: persistence.originals.accessMode 
        value: "ReadWriteOnce"
      - name: persistence.originals.size 
        value: "100Gi"
      - name: persistence.originals.storageClass
        value: "freenas-iscsi-csi"
      valueFiles:
        - /helm-values/photoprism.yaml

        
  destination:
    namespace: photoprism
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
