apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: whoami
    repoURL: 'https://cowboysysop.github.io/charts/'
    targetRevision: 2.5.3
    helm:
      valueFiles:
        - /helm-values/whoami.yaml
  destination:
    namespace: whoami
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
