server:
  extraArgs:
    - --insecure
  config:
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
          
# apiVersionOverrides: 
#   cert-manager: "cert-manager.io/v1"
# repoServer:
#   volumeMounts:
#     - name: helm-values
#       mountPath: /helm-values
#   volumes:
#     - name: helm-values
#       secret:
#         secretName: helm-values
#         #only optional mounts here as on first boot this secret wont be available yet 
#         optional: true